### PR TITLE
Fix proptypes to accept either bool or object

### PR DESCRIPTION
**Pull request by kkerr1**
To prevent quill from injecting style, the style property needs to be
boolean false. Changing proptype to allow this.

### CODE REVIEW

**Comment by kkerr1** [comment]
@zenoamaro yes, thank you!

**Comment by daemonsy** [comment]
Hey @kkerr1 thanks for the fix.  @zenoamaro any intentions to release a small non breaking bump to include this fix? 

Doing prop types validation as a step of our CI and it fails because of this, but we do require passing `false` to styles.

**Comment by zenoamaro** [comment]
Here it is, at last!

Thanks for the patience and all the effort!

**Comment by daemonsy** [comment]
Thank you! :+1:

**Pull request merged**
