### PR TITLE
Fix #179

### LINKED ISSUE #179: When resetting the toolbar and the value, the new value is not displayed.
Hi,

I am using React-quill 1.0.0-beta-4. I just found a small but annoying bug.
I embedded my `ReactQuill` component in a dumb component, so that it gets its `value` and `onChange` callback from the `props`.

The bug I found is reproducible at the following link: http://codepen.io/anon/pen/mWYQav?editors=0010
### How to:
Make sure the toolbar is visible (it normally is). Add some text manually, click on the first button and then on the second one. You won't see the new value being displayed. You'll have to click a second time on the second button to update the value visually.

Could you please confirm this is a bug?

Thank you very much.

### PR DESCRIPTION
**Pull request by rpellerin**

### CODE REVIEW

**Comment by alexkrolick** [comment]
Thank you!

**Comment by rpellerin** [comment]
Any chance you publish this to NPM please?

**Comment by rpellerin** [comment]
Thanks for merging :)

**Comment by alexkrolick** [comment]
We can push a new beta soon. I'd also like to see about adding a regression
test for #179.

>

**Pull request merged**
