### PR TITLE
expose editor's getText to onChange prop

### PR DESCRIPTION
**Pull request by RayOconnor**
The Quill API has a variety of useful functions.  Currently the one I need access to is `getText`.
http://quilljs.com/docs/api/#quillprototypegettext

I added this function to `hookEditor` and tested it locally to ensure that it returns the desired values.

It also appears as though the editor I use (Atom) is automatically deleting tabs on empty lines.  Please let me know if this is a problem, but deleting these seems to be better styling.

@zenoamaro can you merge this when you get a chance?

### CODE REVIEW

**Comment by zenoamaro** [comment]
I found `.getText()` to add some overhead to the change event, that's why I didn't put it there initially. I'm also disliking how many arguments this callback is getting at.

But I think having `getText()` and `getContent()` would be useful, so maybe I'd just need to pass the editor object in the callback, or maybe add a few methods on the component itself. What do you think?

**Comment by RayOconnor** [comment]
@zenoamaro I definitely understand your concern with the number of callbacks getting added, especially because if someone wanted access to another Quill API call on the `editor` they would probably mimic a previous PR and add another... not that scalable... I would definitely like to have access to the editor though.  Quill is pretty powerful. I vote for editor :)

**Comment by RayOconnor** [comment]
just a heads up, I changed the `hookEditor` to only return the `editor`, this could break anything dependent on the `editor.getHtml()` that was passed on before

**Comment by zenoamaro** [comment]
There's a discussion about upgrading to React 0.14 in #35 (which is a breaking change), and I'm thinking of using that as a vehicle to bring this in (which is also breaking).

**Comment by RayOconnor** [comment]
Yeah that would be great.  The sooner I I can get access to the editor or even just the text, the better.  Please keep me updated as to when you think you will make the change.

**Comment by zenoamaro** [comment]
Here are a few options:

- `onChange(value, delta, source)`
  This is how it is currently. Can only retrieve html.

- `onChange(html, text, delta, source)`
  Same issue as before, you can't access the editor if you want, for example, the selection.

- `onChange(editor, delta, source)`
  Cool option, but maybe it's a bit too much to have people do `editor.getHTML()`.

- `onChange(delta, source, editor)`
  This is more like Quill's original event.

- `onChange(html, delta, source, editor)`
  Covers use cases but looks weird.

Anyway, what options do we need to access on the editor?

- `Quill.prototype.getText`
- `Quill.prototype.getLength`
- `Quill.prototype.getContents`
- `Quill.prototype.getHTML`
- `Quill.prototype.getSelection`
- `Quill.prototype.getBounds`

All the other options would imperatively modify the instance under React's nose, so it would make sense to avoid even providing them on the outside. This makes me think:

- `onChange(editor, source)`

  Where `editor` is an object providing or proxying the `getHTML`, `getDelta`, etc. functions.

- `onChange(event)`

  Where `event` is an object with this shape `{ html, text, contents, delta, selection, bounds, source }`. This would be kinda cool, plus it's extendable, except it's evaluating all these props, all the time. So we could get fancy and do:

- `onChange(event)`

  Where `event` is an object in the same shape as above, but containing lazy getters.

This last one looks cool to me, not sure about any downsides. Sure, it's not as minimal as `(value, delta, source)`, and it would probably also need to be done for `onSelectionChange` for consistency's sake.

Maybe we can really go like "fsck the selection, just listen to `onChangeSelection` if you want that", and just go for `(html, text, delta, source)`.

Or even walk the full mile and do `onChange`, `onChangeText`, and eventually `onChangeDelta`.

I'm conflicted. Each choice has its pros and cons, but I have personally only needed the HTML value, so I don't really have a horse in the race. What do you think?

**Comment by RayOconnor** [comment]
Personally I really like the idea of a weaker editor. We shouldn't expose the entire editor because as you said, using any methods that modify the instance would be silliness.  I like the idea of `onChange(rqEditor, source)` (or perhaps a more clever name for rqEditor) where it is clear to the user that they are recieving a less powerful editor that can only use the bulleted methods listed above.

Right now, I need getText, getHTML,  and getLength, but I have been advocating your work among my peers and I could see them wanting to have as much freedom as possible.

**Pull request closed without merging**
