### PR TITLE
Fix: Accessing PropTypes via React package is deprecated

### PR DESCRIPTION
**Pull request by muralikrishna8**
When using the React-^15.3.2 version it is giving a warning message.

screen shot 2017-04-17 at 10 08 53 pm

Added `prop-types` package and accessing the `PropTypes` from this package.

### CODE REVIEW

**Comment by zenoamaro** [comment]
Thanks a lot for the contribution. We're in feature freeze at the moment, but we are definitely considering this for next release.

**Comment by muralikrishna8** [comment]
Thanks 👍

**Comment by btoueg** [comment]
@muralikrishna8 You forgot to change this: https://github.com/muralikrishna8/react-quill/blob/af375348b1e2660725f23cd6bb33e3ece65e9448/src/component.js#L82

**Comment by muralikrishna8** [comment]
@btoueg I've changed that file.

**Comment by btoueg** [comment]
@zenoamaro any chance this can be merged in the near future? It's a fairly innocuous change and would help our team upgrade to react 15.5. Thanks!

**Comment by alexkrolick** [comment]
@zenoamaro Do you think we should migrate to `create-react-class` and `prop-types` for 1.0.0 given the timing?

For everyone else:

- This is just a deprecation warning; the API is still there until React 16. I understand some CI systems complain about any `console.error`, but if that is not a constraint you can still upgrade.
- The reason we are holding back for now (pending discussion) is to avoid introducing a hard dependency that would normally be satisfied by a peer dependency (React > 0.14).

**Comment by Hillgren** [comment]
'We're in feature freeze at the moment'

When do you think the next release will be? :)

**Comment by alexkrolick** [comment]
- 1.0.0 will be soon, as we haven't seen many fresh bug reports lately
- React is downgrading the deprecation errors to warnings for anyone affected by CI failing on console.error: https://github.com/facebook/react/pull/9650

**Comment by alexkrolick** [comment]
We can work on this after #212. Thanks for your patience!

**Comment by mikecousins** [comment]
Can we get this one in now?

**Comment by muralikrishna8** [comment]
> The custom validators that depend on PropTypes must be updated to use the new module: https://github.com/zenoamaro/react-quill/blob/master/src/component.js#L88

I think React.children.only will give the only child it has, otherwise it'll throw an error. In this case if we have children then only we are verifying it should have only one child and it should not be a textarea. So this doesn't change with the PropTypes I guess.
Correct me if my understanding is wrong.

**Comment by alexkrolick** [comment]
Thanks for the contribution. Based on the usage docs for `prop-types` there are a few changes needed:

- [ ] `prop-types` belongs in `dependencies`, not `devDependencies`. https://docs.npmjs.com/files/package.json#devdependencies
- [ ] It should also be marked as external in Webpack: https://github.com/facebook/prop-types#how-to-depend-on-this-package
- [x] The compatible React `peerDependencies` must change to `^0.14.9 || ^15.3.0`
- [x] The custom validators that depend on PropTypes must be updated to use the new module: https://github.com/zenoamaro/react-quill/blob/master/src/component.js#L88

**Comment by haxxxton** [comment]
@muralikrishna8, would you mind also fixing the `Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories` warning with this PR? 

I understand that the PR was originally specifically for PropTypes on React package, but it looks like you've put a lot of extra work in, so what's one more thing right ;)?

**Comment by alexkrolick** [comment]
Closing in favor of #242 which incorporates these changes.

Thanks!

**Pull request closed without merging**
