### PR TITLE
#92 Code block support + Quill Upgrade to 1.0.0-beta.3

### PR DESCRIPTION
**Pull request by Nazanin1369**
- Upgraded QuillJs to version 1.0.0-beta.3 to be able to support code blocks
- Refactored react-quill functions to be compatible with new version of quilljs based on this documentation: http://beta.quilljs.com/guides/upgrading-to-1-0/
- Added code block support to the react-quill
- Made demo page design responsive

### CODE REVIEW

**Comment by zenoamaro** [comment]
Thanks for the contribution!

I would ask you if you could rebase this on master, and only include the code for the _code blocks_ feature.

**Comment by Nazanin1369** [comment]
sure

Best Regards,

**Comment by zenoamaro** [comment]
Latest Quill already supports `code` and `code-block`, and we're deprecating the React Quill toolbar. However, I'm still willing to include this if you can rebase it on the current `master`.

**Comment by alexkrolick** [comment]
I think this is now all covered. If not feel free to reopen.

**Pull request closed without merging**
