### PR TITLE
Update editor component on style updates

### PR DESCRIPTION
**Pull request by lavrton**

### CODE REVIEW

**Comment by zenoamaro** [comment]
The `style` does not concern Quill itself, only its container (which is a simple `<div>` element) so there is no need to update it via `dirtyProps`.

Is there a reason in particular for requesting this change?

**Comment by lavrton** [comment]
This is my component:
```javascript
<ReactQuill style={{
                    ...divStyle,
                    textAlign: this.props.align
                }}
                toolbar={false}
                styles={false}
                value={this.getTextHTML()}
/>
```
In same cases align is changing. But without my update there is not changes in DOM. And this is unexpected.

**Comment by zenoamaro** [comment]
Is `textAlign` supposed to operate on the contents of the editor, ie. align them left? If so, it should be part of the HTML you are obtaining from `this.getTextHTML()`. But they should be aligned left already.

Or is there something else I am missing? What are you trying to align specifically?

**Comment by lavrton** [comment]
You are correct. I am trying to align content of editor. In my application it is global property and should not be part of `this.getTextHTML()`. Of course I can do tweaks in `getTextHTML()` to wrap everything with aligned `div`, but this is workaround.

As `ReactQuill` takes `style` argument I expect that it will update if style are changed. But it is not. And this is unexpected. Don't you think so?

**Comment by zenoamaro** [comment]
There is another attribute, which is `styles` (note the plural), and allows you to inject styles inside the editor document.

See [the note in the README] or [Quill's documentation] for more details, but the gist is that you should pass an object with your selectors and rules to that prop:

    const styles = {
        'ql-editor': { 'text-align': 'left' },
    };

    /* … */

    render: function() {
        return (
            <ReactQuill styles={styles} />
        );
    }

[the note in the README]: https://github.com/zenoamaro/react-quill/blob/53f91fa1123df3eedca74a8f40b9f17cf391d8de/README.md#api-reference

[Quill's documentation]: http://quilljs.com/docs/configuration/

**Comment by lavrton** [comment]
Good. But this is again workaround because updates on `style` property are not working, right? Also I don't need quill styles so i pass `false` to `styles`.

**Comment by zenoamaro** [comment]
It's the opposite, actually: `styles` is the proper way to inject styles into the editor, while `style` does not concern the editor itself, and should not influence it at all if possible. Styling the parent container with `style` and reloading the editor via `dirtyProps` to make it inherit something is the workaround here.

I see you are using `styles={false}`, are you injecting your styles somewhere else? Please, if you could give me as many details as possible on your use-case, those would be appreciated: I would use them to think of a proper official solution for this case.

Thanks

**Comment by lavrton** [comment]
So yes. Styles of editor itself are empty in my case. I am adding some styles via `style` property. And it is good enough (as my styles are very simple). So what was completely unexpected for me is that initial value of `style` was working well, but updates on `style` do not effect component. I spend a lot of type to find the reason of this. Why don't you want to add `style` in dirty props? Are there any performance issues?

Probably other official way is do not allow use `style` property and write note in documentation about it. And probably add this workaround:
```javascript
<div style={youStylesHere}
    <ReactQuill value={value}/>
</div>
```

**Comment by zenoamaro** [comment]
This has been fixed separately in `master`.

However I wish to give you proper attribution for this code in the Changelog.

**Pull request closed without merging**
