### PR TITLE
Fixes "html is undefined" error (Issue #48)

### PR DESCRIPTION
**Pull request by jacktrades**
I *believe* this solves #48.  At least it seems to in my app...

### CODE REVIEW

**Comment by zenoamaro** [comment]
Thanks. I was triaging that issue earlier and committed a different fix. The problem is not so much accessing `props.value` but performing `editor.setHTML(null)`, so I prevented this at the root by having a default in `setEditorContents`.

**Comment by jacktrades** [comment]
Perfect, thanks!

**Comment by jacktrades** [comment]
Whoops, I may have spoke too soon.  3412aaf seems to have the same problem my initial stab at a fix did in that it will overwrite/supersede the `defaultValue` prop.

**Comment by zenoamaro** [comment]
I think we are looking at a different bug here, namely, in [componentDidMount](https://github.com/zenoamaro/react-quill/blob/3412aaf37b8881b9b7b8c15dde2508f21459cdc9/src/component.js#L129):

    this.setEditorContents(editor, this.props.value);

should actually be:

    this.setEditorContents(editor, this.state.value);

As this is overriding the value just after mount, while `state.value` should already have been primed with the correct value [here](https://github.com/zenoamaro/react-quill/blob/3412aaf37b8881b9b7b8c15dde2508f21459cdc9/src/component.js#L84).

Are you able to check on this?

**Comment by jacktrades** [comment]
@zenoamaro using `this.state.value` does fix this (much more elegantly than my hackish solution).

**Pull request closed without merging**
