### PR TITLE
Placeholder, hideToolbar, onSelectionChange features

### PR DESCRIPTION
**Pull request by freakycue**
I've made a fix for #12 and removed some not working code.

### CODE REVIEW

**Comment by zenoamaro** [comment]
Thanks a lot, let me review this.

**Comment by freakycue** [comment]
@zenoamaro, is there any simple way to split PR into several?

**Comment by freakycue** [comment]
@zenoamaro, btw, example 3 in the readme not working in React 0.13 because of undefined ref link. Haven't check it in others.

**Comment by freakycue** [comment]
@zenoamaro, any ETA on this PR?

**Comment by zenoamaro** [comment]
I ended up rewroting event handling to fix issues with controlled / uncontrolled operation, so this, with other changes, makes this PR obsolete a bit.

I'm still interested in your placeholder and custom controls proposals. Could you do a PR for each of them? It's harder to review more than one change at once, especially when there's little time available.

Also, what is it about undefined ref links? Can you open an issue for that?

Thanks!

**Pull request closed without merging**
