### PR TITLE
Update Quill to v1.0.3 (stable)

### PR DESCRIPTION
**Pull request by alexkrolick**
### Updates
Upgrade Quill dependency to 1.0.0 (https://github.com/zenoamaro/react-quill/issues/113 )
- [Quill 1.0.0 Release Notes](https://github.com/quilljs/quill/releases/tag/v1.0.0)
- [Upgrading to Quill 1.0.0 Guide](https://quilljs.com/guides/upgrading-to-1-0/)
- Instructions for using `quill^1.0.0` with `react-quill^2.0.0` [added to README](https://github.com/alexkrolick/react-quill#using-with-quill-10)

### Breaking changes
- Some Quill APIs have changed in a backwards-incompatible manner, including `getHTML`, `addFormat`, and the Toolbar configuration being moved to a module. Please see the official [upgrade guide](https://quilljs.com/guides/upgrading-to-1-0/) and the [new README](https://github.com/alexkrolick/react-quill#using-with-quill-10) for more information.

#### Notes
- Incorporates @clemmy's PR for beta-4, but tracks released Quill versions instead of a forked-and-compiled version. (Note that Quill only distributes `dist/` files for released versions)
- Adds instructions to use new Toolbar module API to the README
- Bypasses use of deprecated `addFormat` API in favor of passing directly to Quill in config
  - For backward compatibility with Quill 0.20, this should perhaps be a configurable option. Depends on whether a breaking change the wrapper is OK since it is providing the Quill dependency.

### CODE REVIEW

**Comment by stevenarnold** [comment]
Do I need special resources of some kind to use this, like fonts or something? I tried using this branch and got some very weird visual effects. Here's a screenshot on Chrome 51 (http://screencast.com/t/tXTJbvdomo) and Firefox 47 (http://screencast.com/t/PlbGkIYFgJpu). I assume it looks and feels good for you, right?

**Comment by alexkrolick** [comment]
You need to include the CSS in your app - how that gets pulled in depends on how your project manages assets. See `node_modules/quill/dist/quill.snow.css`

**Comment by stevenarnold** [comment]
Thanks Alex, that was it. I thought I had that under control, but changing repos broke it.

**Comment by shapiromatron** [comment]
@alexkrolick I could use this as well; anything I can do to help?

**Comment by alexkrolick** [comment]
The fork that this PR is based on is working pretty well for me: https://github.com/alexkrolick/react-quill

The original refactoring to work with Quill v1 was done on @clemmy's branch.

The main question here is whether to make the react-quill configuration API backwards-compatible with the version using the pre-release Quill.

**Comment by stevenarnold** [comment]
Incidentally, this branch is working beautifully for me in dev.

**Comment by alexkrolick** [comment]
Quill v1.0.0 is around the corner - would be great to hash out the upgrade path for users still on the pre-release version. Would love any feedback from anyone actively using this fork.

**Comment by igolden** [comment]
Quill v1.0.0 is here! Will download and checkout this fork today. I need to access the new header option in our app.

**Comment by alexkrolick** [comment]
@igolden v1.0.0 is only at the release candidate stage - there's one more round of testing before it goes out. That said, please check out the fork and report any issues you have upgrading or using the next version of either Quill or this wrapper.

**Comment by alexkrolick** [comment]
Unless anyone *needs it* I am going to not update the fork for Quill rc.1 because it seems like there may be an issue with the bundling of the packaged min.js: https://github.com/quilljs/quill/issues/881

**Comment by alexkrolick** [comment]
Quill 1.0.0 has been released, so I've updated the dependency and bumped the major version of the package at my fork.

**Comment by zenoamaro** [comment]
Thanks for this incredible contribution!

**Pull request merged**
