### PR TITLE
Support adding custom formats to the editor

### PR DESCRIPTION
**Pull request by csk157**
This pull request adds `customFormats` property, which accepts an array of objects, for example:
```javascript
[{
  name: "h1",
  definition: {
    tag: "H1",
    prepare: "heading",
    type: "line"
  }
}]
```

After supplying these, they can be used when defining the toolbar (there is an existing example already how it is done in the `readme`):
```javascript
var toolbarItems = [
    { label:'Text', type:'group', items: [
        { type:'h1', label:'Header 1', value: "H1" },
        { type:'h2', label:'Header 2', value: "H2" },
        { type:'h3', label:'Header 3', value: "H3" },
        { type:'bold', label:'Bold' },
        { type:'italic', label:'Italic' }
    ]},

    { label:'Blocks', type:'group', items: [
        { type:'bullet', label:'Bullet' },
        { type:'list', label:'List' }
    ]}
];
```

I was able to achieve something like this:
screen shot 2015-08-11 at 11 28 53

### CODE REVIEW

**Comment by zenoamaro** [comment]
Superb! Thanks for this pull.

At this point, I'd like to have `formats` accepting both strings for default formats, and objects for custom ones. We could keep a list of default formats around (like in [`Toolbar.defaultItems`]) or simply let it overwrite pre-defined styles. We'd remove `formats` from the options object before creating the editor in `componentDidMount` and apply them back with `setFormats` as you are already doing. What do you think?

I wonder why this isn't already possible in Quill's declarative config? 

Actually, I investigated a bit [how the formats are applied] at config time, and it appears that theoretically custom formats could be passed right into the `formats` option, except the iteration is not composed the right way, so objects never make through to `addFormat` the right way. But, as you showed, we can work our way around it until this is fixed in Quill.

[`Toolbar.defaultItems`]: https://github.com/zenoamaro/react-quill/blob/master/src/toolbar.js#L21

[how the formats are applied]: https://github.com/quilljs/quill/blob/47ee993143c678e2298e38db37faa42566c5a4a6/src/core/document.coffee#L14

**Comment by csk157** [comment]
I like your ideas :+1: , but I couldn't find a way to modify the config of the editor after it was instantiated (`setFormats`).

But it seems that it can still be achieved, if we parse the `formats` array from the props and pass only `string` keys to the editor options and add the new ones after the editor was created.

I will try to implement it later today :)
P.S. I have figured that new formats would be stripped when loading editor with existing content, so I also reload it from the props after adding.

**Comment by csk157** [comment]
The latest commit accepts the following as a format property:
```javascript
var formats = [
    "list",
    "bullet",
    "bold",
    "italic",
    {
        name: "h1",
        definition: { tag: "H1", prepare: "heading", type: "line" }
    },
    {
        name: "h2",
        definition: { tag: "H2", prepare: "heading", type: "line" }
    },
    {
        name: "h3",
        definition: { tag: "H3", prepare: "heading", type: "line" }
    }];
```
The `string` elements are passed into the config for the editor, while `object` elements are added later.
In case the format is not set, it will just pass that to the editors config, which will use quill's defaults.

**Comment by zenoamaro** [comment]
:+1: exactly what I was thinking of.

Given that the value is being set after creation now, I think this could be simplified by passing everything through `addFormat` such as:

~~~js
var formats = [
    "list",
    /* ... */
    { name: "h1", tag: "H1", prepare: "heading", type: "line" }
];

formats.forEach(function(format) {
    editor.addFormat(format.name||format, format);
});
~~~

thus obviating the need for all the type inference, splitting, separating `name` and `definition` namespace, etc. I can see that Quill [tests for an object] so this should work.

[tests for an object]: https://github.com/quilljs/quill/blob/47ee993143c678e2298e38db37faa42566c5a4a6/src/core/document.coffee#L18

**Comment by csk157** [comment]
Cool, this should be what you've described. In case the formats were not set, I pass undefined to quill, so that default formats are used. Otherwise, empty array is passed (not setting any formats).

**Comment by zenoamaro** [comment]
:+1: Great!

If you squash this into one commit and update the pull I'll merge right away.

Thank you very much for your contrib!

**Comment by csk157** [comment]
I squashed it into a single commit and added a few minor fixes (removed unused prop, and updated the readme).

**Comment by zenoamaro** [comment]
There! Thanks again for this awesome feature.

**Comment by csk157** [comment]
I am glad to help :) and thank you for the great wrapper

**Pull request merged**
