### PR TITLE
Update dependencies to support React 16

### LINKED ISSUE #235: New lines added above headings when re-render with the updated text
When I take the result from onChange event and pass it back to the ReactQuill component, it adds a new line above of the lines marked as headings (h1, h2 etc. ). This happens, when there is another text line above the headings. The added option - clipboard: {matchVisual: false } do not have any effect.

Here is a sample, which reproduces the problem:
http://o0.paiyakdev.com/react-quill-issue/

Add few lines with text. Then set the second or third line to be h1, then click on Hidden checkbox few times. There will be new line added above the h1 with every next rendering.

Sorry for my bad english.

### LINKED ISSUE #238: Upgrade Quill to 1.3?
Any plans to upgrade to Quill 1.3?

### PR DESCRIPTION
**Pull request by alexkrolick**
- add prop-types, react-dom-factories, create-react-class
- bump minimim React version to match required peer for above
- add external prop-types pkg to demo

Closes #238
Closes #241
Closes #235
Closes #191
Part of #181

cc @mikecousins I rebased your PR #242 on master and cleaned up the commit log

### CODE REVIEW

**Comment by alexkrolick** [comment]
@zenoamaro Would this and the other recent changes each warrant a minor version or do you want to release them all together as 1.1.0?

**Comment by mikecousins** [comment]
Looks good to me 👍

**Comment by alexkrolick** [comment]
Version 1.10 has been pushed to NPM! Thanks @mikecousins and @zenoamaro for the fixes and features!

**Comment by hmontes** [comment]
Thank you too much!!!!

**Comment by mikecousins** [comment]
Thanks for pushing this out. I've got it running now on our site with no issues seen. Currently running React 16.0.0-beta.3 👍

**Comment by zenoamaro** [comment]
> Would this and the other recent changes each warrant a minor version or do you want to release them all together as 1.1.0?

@alexkrolick, I see no issues in releasing them together. A juicy release 😋

**Pull request merged**
