### PR TITLE
React 0.14 support (Issue #35)

### PR DESCRIPTION
**Pull request by jacktrades**
Here's a proper PR for #35 based off the latest merges to master.

### CODE REVIEW

**Comment by jking90** [comment]
:+1:

**Comment by tkirda** [comment]
@zenoamaro could you please merge this one? Now we are referencing @jacktrades github repo in our package.json, I can confirm that it works with 0.14

**Comment by stephenbunch** [comment]
+1

**Comment by jasonslyvia** [comment]
please merge this!

**Comment by zenoamaro** [comment]
Merged, thanks a lot and sorry for the time this took.

**Comment by tkirda** [comment]
Thank you! Please add it to NPM.

**Comment by jasonslyvia** [comment]
Cool, finally it's merged before my app went to production :joy:

**Comment by aindlq** [comment]
Would be great to have it released on NPM.

**Pull request merged**
