### PR TITLE
Fix editor not being set at mount time

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by browniefed** [comment]
There is no reason to have editor on state. Triggering a setState in `componentDidMount` causes `this.state.editor` to not be set until next tick. 
This means that calling `focus()` will not work in a `componentDidMount`. This fixes these issues of the editor not existing.

**Comment by browniefed** [comment]
Seeing some issues that need to be addressed.

**Comment by browniefed** [comment]
Actually may just be my stuff that is broken but this is an issue

**Comment by zenoamaro** [comment]
I will need to look on this more carefully. I'm not sure what lifecycle guarantees are there for instance properties. But generally I agree with you that editor does not need to be in state per se.

**Pull request closed without merging**
