### PR TITLE
Added check for editor being defined in componentWillReceiveProps.

### PR DESCRIPTION
**Pull request by brucedlukens**
If editor was undefined, it was throwing an error in setEditorContents.

### CODE REVIEW

**Comment by zenoamaro** [comment]
Looks good, thanks!

Would it make sense to just `return` out of `componentWillReceiveProps` if `editor` is `null`?

Do you think this would also happen in the other lifecycle hooks?

**Comment by brucedlukens** [comment]
I only noticed it in componentWillReceiveProps. It was happening when I was unmounting a react-quill component and then mounting a new one right away. It seems like the editor was still destroying itself when it was recreated, causing a delay in the new editor creation? Not sure on the exact cause but editor was undefined on occasion.
You're probably correct, it might be best to just check if editor is defined right off the bat and return out of componentWillReceiveProps. I'm new to using github so I'll update it and attempt to add it to this same pull request.

**Comment by zenoamaro** [comment]
Thanks! You should be able to amend the commit and `push -f`. Don't worry about force-pushing this branch as I'm not keeping a ref on it.

**Comment by zenoamaro** [comment]
Can you squash these two commits together using `git rebase` and then `push -f`?

**Comment by brucedlukens** [comment]
Rebase wasn't working correctly for me on my machine so I just made a new branch with a new pull request. You can delete this pull request.

**Pull request closed without merging**
